### ISSUE TITLE
Excavator can block itself completely when digging

### ISSUE THREAD

**Issue by tLXvGt** [MaFi-Games/Captain-of-Industry-issues#100]
**Describe the issue**
When excavators dig around steep edges it can block itself completely without any valid path of leaving it's current location.

**To Reproduce**
There are no exact steps, my excavator just became blocked by itself.

**Expected behavior**
Excavator should dig in a way not to block itself or at least be able to exit such position (only when blocked).

**Additional context**
 - Game version: Beta 0.3.8 (Steam)

**Attachments**
[first.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7829633/first.zip)
![excavator](https://user-images.githubusercontent.com/17731173/148565106-49219c26-ef20-4675-8941-0696483daf4c.png)

**Comment by MaFi-Games** [comment]
Hi, thanks for the report. I have loaded attached save and seen the issue, it is exactly as you described. 
![image](https://user-images.githubusercontent.com/90082857/148867773-70431cc4-2d74-4207-b83d-e9d69a86cf85.png)

The terrain collapsing and potentially blocking vehicles is part of the challenge of the game. You need to plan your mining operations so that this won't happen to you. This includes making wider plateaus and platforms before digging in to the mountain.

I hope you were able tor resolve this. If you have any other issues, please let us know. Thanks!
