### ISSUE TITLE
Vehicle usage indicator not working properly 

### ISSUE THREAD

**Issue by glilienthal** [MaFi-Games/Captain-of-Industry-issues#1061]
**The issue**
My transports are highly overloaded, lots of transport requests are not fulfilled, but the indicator still says "stable". 

**Expected behavior**
The indicator should give a warning, if transport requests have to wait for a long time. 

**To Reproduce**
Describe steps to reproduce the issue here, for example:
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: 0.5.0c
 - I have a lot of idle vehicles attached to mines, but none for regular transport.

**Comment by MaFi-Games** [comment]
Can you please provide your save file?

**Comment by DeadlyKitten37** [comment]
[buggy save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11794077/buggy.save.zip)

Not the original poster but I have the same issue, I've heard others complain about it as well. I've had the issue a couple times and I managed to get a save to show the issue when reloading.

**To Reproduce:**
Load attached save

Observe this storage is requesting to be emptied but is still full.
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/53106272/c017cc8c-24a2-48ce-ad0f-6059045b2d6a)

Observe there is space to empty it (dumping zone that allows rock and can import from anywhere.)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/53106272/e66acab0-32a3-461d-8786-945faea62118)

Observe the top right which says truck logistics are stable

**Expected Behavior:**
Either all jobs should be completed OR there should be a busy label, currently there is neither.
Currently the display is labeled as stable while the rock is not being dumped.

**Comment by MaFi-Games** [comment]
This was fixed in one of our previous patches. Thanks!
