### ISSUE TITLE
Pickup cannot reach destination 

### ISSUE THREAD

**Issue by r0guec0bra** [MaFi-Games/Captain-of-Industry-issues#107]
![image](https://user-images.githubusercontent.com/31194285/148680559-8a41cda2-1ba3-485b-ba94-224ffc593595.png)
Says  pickup cant reach destination but it shows it going somewhere it shouldn't be!

**Comment by r0guec0bra** [comment]
![image](https://user-images.githubusercontent.com/31194285/148681047-0702002b-599e-47fd-b8d7-cec4868163a9.png)
then this happen

**Comment by fregate84** [comment]
You shoud give your save game or a view of "navigation overlay"

**Comment by MaFi-Games** [comment]
Thanks for your report, from the picture it looks like the storage is blocked by other storage and is indeed unreachable. You can turn off logistics on these storages if you do not wish the trucks to attempt to deliver items there.

If you still think that there is a path to the destinations storage, please attach a save file so we can look into it. A screenshot with navigation overlay as fregate84 mentioned would be also helpful.

**Comment by Richard15665** [comment]
Hello
Im having the same issues, 6 pickups and one excavator cannot reach destination. the excavator isn't out of fuel and is loading a truck as i watch a cross appears on it. also 3 trucks returning to the excavator are also
stopped and are only a short unobstructed distance from the mine
![Captain of Industry](https://user-images.githubusercontent.com/107415272/173370201-93e906a4-cdb7-4156-ac69-74d7af727778.JPG)
.

**Comment by Richard15665** [comment]
So this has to be a bug, why can't it reach the destination
![Captain of Industry2](https://user-images.githubusercontent.com/107415272/173373104-66015901-6a3f-4a77-98b1-b29104520de1.JPG)
?

**Comment by CCampbe11** [comment]
![Image](https://user-images.githubusercontent.com/14852969/174892746-a0090842-60b9-45e4-ae2f-4345ad95ac81.jpg)
Hi! It would be great if trucks could have smarter logic for these issues. For example, it would be great if trucks could ignore the middle storages in this example either by A) having logic to know that they simply couldn't reach them (in the middle) thus ignores those particular storages or B) automatically switch off/grey out the truck import/export when storages etc become inaccessible. The truck toggle you mentioned above is a great workaround, but it would also be great if some logic could be added to handle these particular types of scenarios. Maybe in the earlier issues described above, the grey out option on the truck toggles could be applied when buildings become inaccessible etc to save players toggling each building manually? Or maybe give an information prompt to players warning them that trucks can no longer access a building because it is inaccessible rather than waiting on trucks to tell the player. Just some suggestions! Keep up the great work, enjoying the game!

**Comment by masterquinn** [comment]
Pickups cant reach destination when other pickups are going to exact same location, through same routes... attached save
[proper.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9895980/proper.zip)

**Comment by MaFi-Games** [comment]
This bug has no save or info how to reproduce these issues. The last save provided here has the pickups stuck in a mine that got all its access paths undermined, can be seen on the navigation overlay. Works as inteded.
