### ISSUE TITLE
Nuclear Reactor 2 is consuming Mox Rods but produces Spent Fuel

### ISSUE THREAD

**Issue by michaelberthold** [MaFi-Games/Captain-of-Industry-issues#1114]
### Issue description

If one puts Mox Rods and Uranium Rods into the Nuclear Reactor 2 the Reactor sometimes consumes the Mox Rods but produces Spent fuel.

The screenshot shows the situation. Only the Mox Rods recipe is active but the Reactor is handling the Mox Rods like Uranium Rods and executes the recipe below. But it decreases the number of Mox Rods stored in the Reactor, not the Uranium Rods.

Strangely, the Reactor 2 sometimes work like intended. I can't really tell whats different when the error occours.

Additionally I have to note that I upgraded an existing Reactor 1 with uranium rods in it.

### Reproduction steps

1. Upgrade a Reactor 1 that already was active.
2. Restart the upgraded Reactor 2.
3. Add Mox Rods to the input.

### Game version and build number

1.0.5.2

### Operating system

Windows

### Attachments

![20230614155901_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/38791666/24b1241c-a40f-48a6-8494-12a712689c76)

**Comment by MaFi-Games** [comment]
Once regular rods get into the the reactor chamber they need to get consumed. So this is working as intended. But the UI does not explain it well.

**Comment by michaelberthold** [comment]
Thank you for your reply. In the meantime I checked it as well. The recipe UI does not show correctly what the reactor does. The rods get consumed serially. This is not like other machines do it and that got me tricked :)

**Comment by brubbelmichi** [comment]
Hi,

I just wanted to chime in, because I think this is still an issue. 
My nuclear reactor consumes uranium rods and produces spent MOX.

The situation was the following:
I have a mixed input belt with uranium rods and mox. The internal storage was full with mox and uranium rods. The reactor continued to consume only mox (which is what I want), so the internal storage went down, which is expected behaviour, because I think the storage of 80 is actually dedicated 40 mox and 40 uranium rods. 
So the storage went down to 40/80 because the next item on input belt was a uranium rod, but the uranium storage was full, so nothing made it into the reactor.

Now the following accured:
The mox rods went down to zero, but the mox recipe still went on. But now it consumed uranium rods (still showing the mox recipe being active) and it output spent mox, regardless whether a mox or a uranium rod was consumed.

Below a few screenshots to maybe help illustrate the issue:
Only 1 mox rod left:
![20230627122049_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137888691/5441312d-afc0-4667-b995-b0be1dd637f3)

last mox rod being consumed:
![20230627122254_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137888691/356e471b-0887-4560-9d62-30d37b55a5cb)

consuming uranium rods and outputting spent mox (see belt)
![20230627122318_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137888691/ec57cecc-6a26-439e-bc10-5ccc450c1c34)

After a reload of the map and deactivating the mox recipe, it still woudn't work as expected:
![20230627122825_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137888691/ee6e5d76-906b-4bbf-a96a-43f1231c6fd3)

Maybe important: The reactor startet up on uranium rods producing spent fuel (the yellow one), and after putting mox fuel in it, it still was producing spent fuel, but consuming mox, so the exact opposite of what my issue is now. It somehow fixed itselt, can't tell you why or how though, sorry :/
