### ISSUE TITLE
Game crased

### ISSUE THREAD

**Issue by Andreja40** [MaFi-Games/Captain-of-Industry-issues#1211]
### Issue description

The problem is that the game stops, it always works for 1 minute or 2, then it just freezes.The game just freezes and I can't do anything. I can just shut it down. Then I restart it but after 1 or 2 minutes it freezes again I need help.....

### Reproduction steps

If you don't have anything to do, the game just freezes.

### Game version and build number

v0.5.3e b225

### Operating system

Windows

**Comment by MaFi-Games** [comment]
In order to investigate this issue, we will need more info. Ideally, a save that is causing this, logs, and probable cause if there is any. Logs can be found in `%USERPROFILE%/AppData/Roaming/Captain of Industry/Logs`, `%USERPROFILE%/AppData/LocalLow/Mafi Games/Captain of Industry/`, and `%USERPROFILE%/AppData/Local/Temp/Mafi Games/Captain of Industry/Crashe`.

**Comment by MaFi-Games** [comment]
Closing as there is not enough information. But it seems like this might be a hardware issue.
