### ISSUE TITLE
access is denied

### ISSUE THREAD

**Issue by witenight** [MaFi-Games/Captain-of-Industry-issues#1218]
### Issue description

gettting access is denied (0x5) when i try to start the game and when i try to use the  the main exe and i get windows cannot access the specified device,path,or file. you may not have the appropriate .

### Reproduction steps

just try tostart the game

### Game version and build number

i can not see it 

### Operating system

Windows

**Comment by witenight** [comment]
need help

**Comment by MaFi-Games** [comment]
This might be due to some anti-virus software you have installed that improperly treats CoI as a virus. You might need to set up a custom rule in that particular anti-virus to allow the game to run. It would be great if you could also file this issue with that anti-virus company so they improve their rules. Also you might need to have your local files of the game rechecked by Steam for integrity so it restores any files missing.
