### ISSUE TITLE
Trucks extremely busy and idle at the same time

### ISSUE THREAD

**Issue by taviLaies** [MaFi-Games/Captain-of-Industry-issues#1228]
### Issue description

Hi, I'm running into an issue where my trucks are extremely busy but a bunch of trucks are idle at the same time.

My entire world is collapsing as I'm watching trucks sitting around.

Happy to help troubleshoot further.

### Reproduction steps

1. load save
2. observe status and idle trucks
3. let the game run and observe it's not getting better

For example, in the NW I have 2 unit storages full of wood and a big storage just north of town that is not getting filled up.

### Game version and build number

v0.5.3e b225

### Operating system

Windows

### Attachments

![Screenshot 2023-08-11 180739](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/16595179/916d6ec4-90b2-4821-983b-b89a7fa414e5)
[1.green.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12325924/1.green.zip)

**Comment by MaFi-Games** [comment]
It can take a second before a vehicle gets a job so it may appear idle for a while. The real issue here is that you lack enough of T2 trucks (10 at least). You have an excess of haul trucks but these can't carry countable products. Also if you'd replace the output storage for wood with a large storage that would also help a lot with throughput as at this point the smaller storage can have at most 4 trucks arriving at any time.

**Comment by taviLaies** [comment]
Thank you for the explanations. That is very helpful.

One piece of feedback: I would like more information that helps me troubleshoot these issues:
- a filter in the Analytics tab that lets me exclude trucks assigned to buildings (e.g. trucks designated to empty storages)
- more details on jobs that are in the queue to allow me to troubleshoot an unexpected long queue
- details on looping jobs (trucks picking up from container 1, delivering to container 2, only to move them back to container 1)

I will close this issue.
