### ISSUE TITLE
Invisible Entities

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#1249]
### Issue description

Some users are experiencing invisible entities:
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/10c0382d-b352-4815-8e30-5e25e52ac1fe)

### Reproduction steps

Can't replicate

### Game version and build number

v0.5.4f

### Operating system

Windows

### Attachments

[23-08-08_14-06-48_6379.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12477195/23-08-08_14-06-48_6379.log)
[Player(1).log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12477196/Player.1.log)

**Comment by zuff-coi** [comment]
Flamescowl from discord provided their information:

Specs:
10700KF, 32GB Ram, 4090 RTX 

Other details:
before that ghost thing occure, i copyed massive buildings 
and run game very long ( maybe at leat 9hour )

Logs: 
[23-08-26_12-02-33_7255.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12487857/23-08-26_12-02-33_7255.log)

Saves:
[save_23-08-26_22-25-20.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12487867/save_23-08-26_22-25-20.zip)
[save_23-08-26_10-40-36.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12487870/save_23-08-26_10-40-36.zip)

Gifs:
![Honeycam_2023-08-31_22-40-08](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/612bfaac-43fd-436c-bb13-ca05d0bf9790)
![Honeycam_2023-08-31_22-41-35](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/5a4c185b-f934-484f-906c-f6faaccf98fc)

**Comment by JoelmutiOS** [comment]
[23-09-28_13-55-33_2684.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12776178/23-09-28_13-55-33_2684.log)
[YSNP5.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12776186/YSNP5.zip)

Hi there I have also had invisible entities happen once.
Save file, log and screenshots are attached. 
The game had been running for around 12 hours, I had regularly tabbed between yt and coi as well.
Specs are i5 9600k, 32gb ram, 2080 rtx
Game version v0.5.5 is on the load screen.

I had quick built a electric boiler when I realized it was invisible save for the ground footprint, so I quick removed it and rebuilt it but it was still invisible. I then tried some other entity but it seemed anything new would be invisible. So I checked here to see it was a known bug and closed and reopened the game which fixed the issue.
Has not happened since. 


![20230929035951_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/28531222/3cbf2c4d-aa7a-46f6-b7a2-6091976efb57)
![20230929035947_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/28531222/15b814af-5269-4757-a071-7ed4b9c0ee30)
![20230929035929_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/28531222/e979b128-836c-44f0-8e47-0fc9e133f428)
![20230929035918_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/28531222/acd4992a-16db-4d7a-a7fb-ed47187154b2)

**Comment by zuff-coi** [comment]
[RealisticOptimist had this to say on discord](https://discord.com/channels/803508556325584926/883590993063051275/1172155538843369553):
> I might have a hint regarding the disapearing buildings. Happened first time to me. I clicked a maintenance depot basic just before it upgraded to a maintenance depot. From there on, even a new maintenance depot remained invisible. Interestingly, the depots both got an irrigated farm outline when clicked.
> Needless to say, after reloading it was gone.

![MaintDepot](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/1a820116-82fc-49b1-97bf-c59245ed9395)
![MaintDepot2](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/98e5f3ca-16a9-4aa6-8da9-44a01c50900a)
