### ISSUE TITLE
Dumping control ignored

### ISSUE THREAD

**Issue by martinjh** [MaFi-Games/Captain-of-Industry-issues#1280]
### Issue description

Area is controlled by Mine Control Tower with dirt defined as only material allowed. Game is allowing dumping as defined in Stable (rock waste, slag)

### Reproduction steps

Load attached save and view attached screen shot
Behaviour is visible near oil terminal

### Game version and build number

v0.5.5 b246

### Operating system

Windows

### Attachments

[captain2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12672897/captain2.zip)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/191531/c98cb82d-694c-4097-aab2-f9c3bc4e8f2a)

**Comment by JamieRCHI** [comment]
Not saying this is the answer, but this is why it happens to me.
I have noticed if the list of items that are allowed to dump are changed, the game will continue dumping the undesired items for awhile. 
Most likely due to how the game is designed. Current items in the command que will continue to happen. 

The best way to avoid this is to remove all dumping designations (green squares), Change the 'What can be dumped here' stuff, and then replace the dumping designators. 

Other than what I posted above, I have never seen this happen.

I would say, Closed, No repro.
