### ISSUE TITLE
Corrupt save file

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#1347]
### Issue description

hi Captains, 
this save files is corrupt, the save before that worked. Sin

ce the user in discord didnt provide much information about except that he dont use mods (escapt for 1 mod to deleted trucks) it seem like a save issue. 

Since the language barrier was a issue i post this instand of he is doing it. Maybe it is a issue when saving the game or just bad luck. 

[24-01-24_17-34-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14068157/24-01-24_17-34-autosave.zip)

To reproduce the bug just try to load the save a error message will pop up. 

### Reproduction steps

Load the save a error message will show up when the save is in process of being loaded.

### Game version and build number

v0.5.5d b259

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Would you happen to know if you were playing a built in map or something you downloaded?

**Comment by MaFi-Games** [comment]
Thank you so much for the report and sorry for our delayed response. It took us some time to figure this one out, it was a complex issue, but we believe that this has been fixed in v0.6.3. Unfortunately, the attached save cannot be restored as the file was only partially written. I will be closing this now, but if you have further issues please let us know or create a new issue.
