### ISSUE TITLE
All truck struggling to find a destination it can reach.

### ISSUE THREAD

**Issue by ScottGiles** [MaFi-Games/Captain-of-Industry-issues#1459]
### Issue description

I have been playing on the Armageddon Map (start #3) with 0.6.X   I autopatched to 0.6.2a (b328) overnight, and now all my trucks are getting confused and can no longer find any places to dump stone/dirt/etc.  Adding a new place to dump seems to temporarily help, but any long-range dump sites are ignored, even ones that were used when playing with v0.6.2

### Reproduction steps

Load save.
Wait for trucks to all decide to do nothing.

### Game version and build number

v0.6.2a b328

### Operating system

Windows

### Attachments

[current.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15018379/current.zip)

**Comment by MaFi-Games** [comment]
It's because the dumping designations are not continuous, there's a peak and then 1 level lower is a the flat ramp. I fixed that to be continuous and all trucks started dumping there.

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/90082857/04a48da8-eced-426d-99bc-3fcdaf76161c)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/90082857/aa00acaf-24fb-4eab-afe9-c2ca7c270562)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/90082857/4676a37c-f721-4879-ae29-d370d825f58b)
