### ISSUE TITLE
Pipe merging ( wasted water + Acid Water ) stop working between update 6.2.2 and 6.3.3a

### ISSUE THREAD

**Issue by stratege1401** [MaFi-Games/Captain-of-Industry-issues#1481]
### Issue description

Two pipes merging in one. Using simple  Pipe one is transporting wasted water. Pipe two acide water. Used to go through a liquid dump, with all recipe active. Before update 0.6.3a used to work ( i bought the game and started with v 0.6.2 ).
Same using simple merger or balance merger. 

### Reproduction steps

- Load game
-  Look a merger very next to harbor, with 2 fluid storage and the piping going left side of the map.
- 

### Game version and build number

U2|v0.6.3a (b333)

### Operating system

Windows

### Attachments

![24-04-25_17-42-34_y94_pop590](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8655165/8818c255-7ac9-4fd9-980c-42667f2eff37)

**Comment by stratege1401** [comment]
oupsss, saved games of course ...
[BUGPIPEMERGE.zip.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15113582/BUGPIPEMERGE.zip.zip)

**Comment by MaiLunJiye** [comment]
### Issue description

In the game, sometimes it is necessary to use a pipeline to mix and transport liquids（Such as chemical fertilizers and organic fertilizers）, but in the current code implementation of the pipeline, one liquid must be drained before another liquid can be injected. Therefore, when the pipeline is relatively long, it takes more time to empty the pipeline and, making the long pipeline very inefficient when transporting mixed liquids.

### Reproduction steps

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/20548127/e7811504-9bbe-4dd7-971a-f83599e7383f)

The two liquid tanks above are very inefficient at emptying, and looking at the longer pipes, you can see that you have to wait for one liquid to drain before transferring the next.

### Game version and build number

v0.6.3a b333

### Operating system

Windows

### Attachments

_No response_

**Comment by MaFi-Games** [comment]
It was always like this. By design pipes in COI don't support mixing.

**Comment by Feelosov** [comment]
Well, then the logic in all this is flawed. Because I designed the factory based on the fact that different liquids could flow through a single pipe and that the drain pipe could have multiple recipes running simultaneously, but waiting for a pipe over 50 cells long to empty is completely incorrect. 

We should either disable the ability to run multiple recipes on the drain pipe simultaneously (forcing a drain pipe to be built for each liquid), or eliminate this delay and run both manganese and glycerin through the same pipe simultaneously, and add a difficulty setting for enabling/disabling the mechanics. 

I'm not satisfied because I was relying on the drain pipe being able to handle multiple liquids simultaneously. But the game is perfect.

Upd 3 | 0.7.9a (b500)
