### ISSUE TITLE
Truck pathing around impassable dirt edges

### ISSUE THREAD

**Issue by Jemsterr** [MaFi-Games/Captain-of-Industry-issues#1491]
### Issue description

Trucks Path a straight line with an impassable dirt edge in the middle. Reaches the barrier, and goes around the end, comes back to point where it reached the barrier and continues from there.

Instead of following the green path (expected), they follow the red path:

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/17609227/a564fe5f-9287-421e-a9a4-4251e8ad487f)

Note: [CoI Extended](https://github.com/Keranik/COI-Extended/releases) all-mods required to load save.

### Reproduction steps

1. Load attached save
2. Watch the trucks at the corner run at the grass, then go around in a weird way.

### Game version and build number

v0.6.3a (b333)

### Operating system

Linux

### Attachments

[Trucks pathing.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15174998/Trucks.pathing.save.zip)

**Comment by basox70** [comment]
### Issue description
Same issue here
Some trucks takes red path instead of blue path (if it doesn't change at save load, I have 3 trucks taking the long path after the ship arrive)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/6689304/7c8fbbaa-4a8b-438b-b522-71ebdaaa959c)

### Game version and build number
no mod used
Using V0.6.4 (b337)

### Operating system
Windows 11

### Attachments
[Coal truck path.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15347098/Coal.truck.path.zip)

**Comment by CaptainMarek** [comment]
Thanks for the report, this have been fixed in v0.6.4a (currently in the experimental branch).
