### ISSUE TITLE
remapped keybinds still assigned to camera movement

### ISSUE THREAD

**Issue by Erah101** [MaFi-Games/Captain-of-Industry-issues#281]
**Describe the issue**
i swapped Z/W and A/Q to play with an azerty keyboard but the default camera movement keys (A/W) are still assigned so now opening the dumping UI also moves the camera up (pressing W) and lowering the tool in that menu also moves the camera left (pressing A)
also pressing Q+Z combo moves upper left, S+D combo moves down right (as expected) but pressing Q+S or Z+D doesn't move diagonally

**Expected behavior**
remapped keybinds should no longer be assigned to default ones

**To Reproduce**
set your windows to an azerty keyboard layout (french)
swap A/Q and Z/W
try moving the camera around

**Additional context**
0.4.2

**Comment by Erah101** [comment]
restarting the game didn't change anything

**Comment by CaptainDapper** [comment]
Oh wow you opened this ticket as I was writing mine. lol.

**Describe the issue**
rebinding from WASD to ESDF doesn't completely work; E and F do move the camera up and right, but S still moves down, and D still also moves right. W and A still do Up and Left.

**Expected behavior**
WASD to properly remap away from previous behaviors

**To Reproduce**
Steps to reproduce the behavior:

1. Rebind WASD
2. Be sad


Game version: EA 0.4.2

**Comment by MaFi-Games** [comment]
Thanks for reports, this was fixed in v0.4.2a.
