### ISSUE TITLE
Excavator fails to dig up multiple terrain types/

### ISSUE THREAD

**Issue by theman83554** [MaFi-Games/Captain-of-Industry-issues#31]
**Describe the issue**
When an excavator is digging a tile with multiple terrain types (Dirt and rock). It sometimes fails to actually load a shovel full. The excavator animates multiple times in a row but the information window says it's empty and it's not dumping into the truck.

**To Reproduce**
Mark a tile with mixed terrain for excavation, wait until it fails. 

**Expected behavior**
I'd expect it to take a partial load of whatever terrain type it picks nd load it as normal.

**Additional context**
 - Game version: 0.2.8

**Comment by MaFi-Games** [comment]
This sometimes happens when there is not enough material removed from the terrain and gets converted to 0 quantity. When multiple materials are mixed on top of each other, like dirt on rock, sometimes removing the thin layer of dirt will cause this. We have ideas how to improve this but it is not a high priority now. I will leave this open for now as a tracking issue. Thanks!

**Comment by MaFi-Games** [comment]
Excavator mining procedure was improved in upcoming beta release, thanks for reporting!
