### ISSUE TITLE
Excavators dig through walls

### ISSUE THREAD

**Issue by Honcharuk** [MaFi-Games/Captain-of-Industry-issues#318]
Excavators dig through walls. Excavators must not dig through walls
 - Game version: 0.4.3
![20220612151038_1](https://user-images.githubusercontent.com/15582553/173232644-6a5c5c38-40db-47d8-baa8-32e199355ab4.jpg)

![20220612151034_1](https://user-images.githubusercontent.com/15582553/173232639-36143e2d-1c99-467c-b268-309605ff6c00.jpg)

**Comment by JamieRCHI** [comment]
Yes. Even when retaining walls not placed on an area being mined, material on the other side of the walls will trickle down into the mining areas. This is really bad when digging in sand. Walls should block everything both ways.

**Comment by lowstrife** [comment]
The problem: Excavators can dig behind retaining walls and grab the circled dirt. Simple enough. 
![image](https://user-images.githubusercontent.com/65734844/185971669-7e8caa0d-6f16-4ad6-bdd5-62b2d4aeb54b.png)

Another situation where this is sub-optimal. The retaining walls are lined up perfectly with the mining area. 

I knew of the issue where a excavator could dig behind a retaining wall so I lined up the footprint of the retainer with the mining area. Nope. Excavator still digs behind and gets dirt from somewhere and collapses the whole deal. 

![image](https://user-images.githubusercontent.com/65734844/185971259-91323462-818a-4c32-b5dd-ddcda6cf0f1d.png)

![image](https://user-images.githubusercontent.com/65734844/185971298-6a40873d-abd7-4a87-86c9-c81dc318aac9.png)

The situation I just described, the retaining wall was oriented as per figure 1. The only solution that prevents it from happening is orienting the retaining wall in figure 2.

![image](https://user-images.githubusercontent.com/65734844/185971923-89b87155-38a6-471d-9698-bd721609252e.png)

**Comment by Jeferson-Emanuel** [comment]
As discussed in the discord server, the desired way of use of retention walls is like this:

[https://cdn.discordapp.com/attachments/883590993063051275/1011284257638989884/unknown.png](url)

But, because the current behaviour of excavators is to dig the whole square, it simply removes the terrain that is in the other side of the walls in the lower level, causing the upper level of walls to crumble.

It forces us to use walls like this:

[https://cdn.discordapp.com/attachments/883590993063051275/1011283263211442196/unknown.png](url)

Suggestion: The default square used to designate areas to be mined is composed of a smaller grid of 4×4. You can see them when you try to place retention walls with their top, or it's base at the exact ground level. Any of these small squares is checked, if any of it are over/below the ground level you get an error that the terrain is too high/low to allow construction. I suggest using something like it to allow excavators to recognize what are the limits of a retention wall, and only mine the area that is not blocked by them.

Another suggestion: Make the retention walls have some kind of collision that will prevent the arm of the excavator to simply pass through it. Creating a literal barrier that will block everything in both sides of the wall. Preventing excavators to dig through it, and dumped terrain to pass to the wrong side.

**Comment by RascallHunter** [comment]
A few possible thoughts for effective ways to tackle this:
1) have walls snap to the major designation grid so the walls are centered over the grid lines, and intersections snap to the corners of grid squares. Relatively simple to implement, but it reduces the flexibility of placement of the walls. Not a great solution in my book.

The approach mentioned above where the wall registers as a barrier to excavators and trucks is another possibility, but I would guess would come with a fairly hefty rewrite of code to update the way excavators and trucks work now? Not sure. Would probably work reasonably well if i cmt can be implemented in a way that doesn’t hit performance.

Allow 1/2 and 1/4 size designations (or have wall segments block creation of designations within their footprint).  Not sure if either part of this is even possible without a significant overhaul of the designation system. 

Being able to put walls with minimum setback of base of one wall next to the top of the next one would allow walls to created steeper slopes than rock alone does (10 per designation block rather than 7 that rock can do), and increase the utility of them.

**Comment by zuff-coi** [comment]
With the latest experimental patch v.0.4.11, you can no longer apply mining or digging designations to squares that contain retaining walls. 

You can also no longer place retaining walls on squares that have designation.
