### ISSUE TITLE
Crash repport

### ISSUE THREAD

**Issue by godifreyI** [MaFi-Games/Captain-of-Industry-issues#321]
**Describe the issue**
The computer got a hard crash (freeze and reboot) sometimes at saving (auto or manual). Some saves work.

**Expected behavior**
Not crash

**To Reproduce**
Nothing particular

**Additional context**
 - Game version: 0.4.3

**Attachments**
[save_22-06-12_18-54-51.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8886505/save_22-06-12_18-54-51.zip)

**Comment by MaFi-Games** [comment]
I  can't reproduce any issue on that save file.  Please share us your logs You can find them in your Documents (%userprofile%\Documents\Captain Of Industry\Logs). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from %USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\. You might need to ZIP the attached files.
