### ISSUE TITLE
Invisible materials on conveyors 

### ISSUE THREAD

**Issue by Kazzaxx** [MaFi-Games/Captain-of-Industry-issues#359]
**Describe the issue**

Hi, I am in late game and when I load and start game, all materials on conveyors will become invisible. Its still here, but not visible.

**Expected behavior**
Should be visible.

**To Reproduce**
1. Load attached save '...'
2. Unpause

**Additional context**

0.4.4c

**Attachments**

[save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8923595/save.zip)
![Captain Of Industry Screenshot 2022 06 17 - 02 51 10 72](https://user-images.githubusercontent.com/107657952/174201321-6fe9377d-a8aa-4b80-9c64-1c58474fb21f.png)

**Comment by utdrmac** [comment]
Please give this issue a better title. Simply calling it 'Bug' is no help.

**Comment by MaFi-Games** [comment]
Thanks for reporting this! This has happened because some of your transports are extremely long and we need to add a limit on that, we should not allow that as it hits some of our internal optimizations. There isn't much we can  do to recover this unfortunately. Can you return the to point before you've built the massive transports? Easy solution is to build shorter ones and have them split with mini-zipper.

**Comment by Kazzaxx** [comment]
> Thanks for reporting this! This has happened because some of your transports are extremely long and we need to add a limit on that, we should not allow that as it hits some of our internal optimizations. There isn't much we can do to recover this unfortunately. Can you return the to point before you've built the massive transports? Easy solution is to build shorter ones and have them split with mini-zipper.

Unfortunately, I don't have an older save. But I really enjoy the game, so no problem will start again. I'll try another map. Thank you for the answer and great game.

**Comment by MaFi-Games** [comment]
This should now be fixed in v0.4.6. Long transports are no longer allowed and if they are built they will not break the game anymore.
