### ISSUE TITLE
Generators don't turn off properly

### ISSUE THREAD

**Issue by ParanoikCZE** [MaFi-Games/Captain-of-Industry-issues#538]
**The issue**
During longer rainy months, my buffer flywheels get depleted but generators don't turn off themself blocking the shaft to get power again during sunny days. Solars have set priority 1, while generators 9-11
![obrazek](https://user-images.githubusercontent.com/19796452/178072179-8fe343b1-a774-4909-8e3c-d858b82b68e0.png)
Setup: ![obrazek](https://user-images.githubusercontent.com/19796452/178072334-e355b244-6707-4725-ba82-c61f5564e7a9.png)

**Expected behavior**
Generators turn them off accordingly to their priority.

**To Reproduce**
I've tried to find exact steps but looks like it's happening randomly. Anyway, in the attached save, there are all generators on the low-pressure turbine shaft in this state.

**Additional context**
0.4.7d

**Attachments**
[Generator.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9075098/Generator.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report. This currently works as intended. Power generators need some minimal input to even start generating power. In case of T2, they start producing power at input of 1kw of mech power. The save has one 2 kw turbine trying to power 12 kw worth of generators. The generators get 500 each but won't produce any power since they are below the threshold.

We might re-balance this or change how power is delivered on shaft (perhaps prefer one generator instead of even split) but there is no bug here.

**Comment by ParanoikCZE** [comment]
Seems like this ticket ended in some kind of zombie state too :D
I assume (based on changelog) that it was fixed in v0.4.9b
