### ISSUE TITLE
Vehicles Mangement, add trucks job queue

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#601]
### Issue description

Feature request. 

I'd like to see the trucks job queue. Presentation could be like the Trucks Cargo History, in an additional tab. See also #600.

While the history is helpful to understand where to build new transports, seeing the job queue could help the player handling the "extremely busy", e.g. by pausing some construction ...

### Expected behavior

General idea see above.

Should ongoing jobs be included?!

Special states of trucks might have to be considered, like no destination.

### Game version

v0.4.8

**Comment by MaFi-Games** [comment]
Truck job queue does not exist. Jobs are calculated in real time and only when needed. We could do just some estimates but we are currently focusing on other areas.

Otherwise, please file features ideas here: https://ideas.captain-of-industry.com/ We track bugs here or feature requests that are significant improvement in some major frustrating situations.
