### ISSUE TITLE
commands_history.txt permission issue

### ISSUE THREAD

**Issue by Ramcoch** [MaFi-Games/Captain-of-Industry-issues#710]
### Issue description

game failed to initialise

### Expected behavior

game to start

### Game version

v 0.4.9c

**Comment by zuff-coi** [comment]
Could you please provide some more details regarding this issue?

We'll need your log files found in two locations:
You can find your logs in both `Documents\Captain of Industry\Logs` and `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`

Thanks

**Comment by Ramcoch** [comment]
log file as requested

[22-08-14_20-37-54_2722.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9333992/22-08-14_20-37-54_2722.log)

**Comment by zuff-coi** [comment]
Thanks for the logs @Ramcoch 

`UnauthorizedAccessException: Access to the path "C:\Users\ramsa\Documents\Captain of Industry\Console\commands_history.txt" is denied` is the culprit.

We will patch the game so that this doesn't happen again but you may run into other issues because you're computer isn't letting COI write to that folder. To prevent future issues, check your Controlled Folder Access toggle which can be found under Ransomware Protection:
![image](https://user-images.githubusercontent.com/108291414/184555949-6ef12287-babc-4d93-9c81-cd3639980383.png)

If it is on you can either turn it off or add an exception by clicking "Allow an app through Controlled Folder Access listed at the bottom of this screenshot:
![image](https://user-images.githubusercontent.com/108291414/184555916-f6ebe951-94ce-4303-b292-a08e27ed91f1.png)

**Comment by Ramcoch** [comment]
managed to sort problem. Changed the permissions for the file. Everything working fine. Thank you for your help

**Comment by MaFi-Games** [comment]
I believe we have fixed this in our last patch.
