### ISSUE TITLE
Trucks dumping waste in a dedicated sand hill.

### ISSUE THREAD

**Issue by VernonJv** [MaFi-Games/Captain-of-Industry-issues#785]
### Issue description

Trucks started to dump waste in a sand dump.

For a long time I used this area to dump excess sand as I was terraforming.  For some reason in the last few minutes trucks filled with waste have started to dump there.

You can see from the pictures the initial area is waste free untill recently.  
I have tried to pause / unpause the mining tower.  I have tried adding and removing waste and sand to see if this changes but to no avail.

![Captain of Industry Screenshot 2022 09 12 - 19 54 53 11](https://user-images.githubusercontent.com/112779559/189734239-62b54934-1a79-49e7-b4fe-03c3ee34ed86.png)
![Captain of Industry Screenshot 2022 09 12 - 19 55 12 57](https://user-images.githubusercontent.com/112779559/189734311-0393c955-ed95-4a2f-a6e7-6411a45e8f8a.png)

While writing this the trucks are now also dumping rock.  I assume this is a bug....

![Captain of Industry Screenshot 2022 09 12 - 20 00 39 52](https://user-images.githubusercontent.com/112779559/189734768-7bd5cd28-abc5-45b2-b87f-65c1445a45e5.png)

### Expected behavior

Expect towers to only allow dumping of specified materials

### Reproduction steps

Not sure has worked fine till now

### Game version

v 0.4.11

### Attachments

[22-09-12_19-53-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9551049/22-09-12_19-53-autosave.zip)
Save file attached

**Comment by MaciejPolanski** [comment]
Hi,

I hope you don't mind me taking a look at your savegame.
So sand heap overlays with another mine area, that allows a waste to be dumped. Move that area elsewhere or remove non-sand disposables.

_Let me also comment that heap dumping in this game is insanely complicated. The number of times I have had waste dumped on my future farmfield simply because: I forgot it was inside the mine area, as a side effect of changing the mine boundaries, or because the global settings were different than I thought, or by changing the global settings, or because the area was part of another mine I thought of, simply cannot be counted. And mine building looks silly if building a seaport._

_This game need simple system, where dump has nothing to do with mine, it is a simple flag to be placed, draw a shape and set a disposables. No movable areas, no global settings, buildings and so on._

![20220912233851_1](https://user-images.githubusercontent.com/25035071/189763737-a94b556c-4dd4-4dad-90a1-d584fbf0325b.jpg)

**Comment by VernonJv** [comment]
Ah yeah that explains why it was fine for ages then when it hit the line of the other area it messed up. 

Thanks for the help 👍
