### ISSUE TITLE
Gold powder

### ISSUE THREAD

**Issue by Giedriukss** [MaFi-Games/Captain-of-Industry-issues#789]
Crusher use 48 gold ore crushed but only gives 24 gold powder. But shuld give 48 gold powder

**Comment by zuff-coi** [comment]
This is because you have Show / 60 toggled on:
Here it is on:
![image](https://user-images.githubusercontent.com/108291414/191291901-a63fb625-ceb3-46ba-a21f-a1230d1cae37.png)
And here it is off:
![image](https://user-images.githubusercontent.com/108291414/191291942-e755d7e8-0b7b-447f-b289-a7dcc70e0b59.png)

Show / 60 gives you the output per 60 seconds instead of the machine's run time so you can better understand your ratios for other machines.
