### ISSUE TITLE
Assembly unity boost speed hack

### ISSUE THREAD

**Issue by NotoriousPyro** [MaFi-Games/Captain-of-Industry-issues#820]
### Issue description

If you wait long enough for the bar to almost complete and then hit the unity boost button, the product will complete early. You can then immediately remove the boost, thus skipping around a 1/3rd of the time you'd have to wait for the product, at no extra cost.

### Expected behavior

There should be a penalty or cooldown between activating unity boosts.

### Reproduction steps

1. When the assembly product completion bar is near 2/3rds, boost it with unity.
2. Observe the product is delivered early.
3. Un-boost the assembly, note the product still exists in the output.
4. Wait until the assembly reaches 2/3rds again, and boost it with unity.
5. Ad infinitum. Can be done with several to get tonnes of items quickly.

### Game version

0.4.12

**Comment by MaFi-Games** [comment]
I don't see any issue here. Yes, the progress jumps forward but that does not really matter as the boost is paid f or viaUnity so it is not free. Perfoming these operations subsequently also does not give any benefit compared to letting the boosted machine just run, because the machine is twice faster when boosted all the time. Doing it this was of switching from boosted to non-boosted would make it actually even slower.
