### ISSUE TITLE
Getting "Truck has no fuel" when a station is close by

### ISSUE THREAD

**Issue by Jaydirl** [MaFi-Games/Captain-of-Industry-issues#846]
### Issue description

On a Curland Island I am harvesting trees on the opposide side of the island.
I have a fule station close to that area, but the trucks will just run out of fuel and throw an error.

I manually send to the station where they sit for a while until they get fuel and continue until next time.

### Expected behavior

I expect the trucks to find a place to fuel up and not throw this error.

### Reproduction steps

Please see my attached save file
[NoFuel.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9661129/NoFuel.zip)

Repo Steps.
You may need to update the trees to harvest but in time the error should pop up on the screen.

### Game version

v0.4.12E

**Comment by MaciejPolanski** [comment]
I hope you don't mind me looking on your save.
The problem seems, for me, to be inadequate space for wood. Fuel message is just incorrect. Adding storage makes pickup run: https://streamable.com/jctmxj
Don't be fooled by the apparent empty space in the storage; it may be reserved for trucks on the move.

**Comment by MaFi-Games** [comment]
We have fixed that we were reporting no fuel when trucks just could not deliver cargo, we also no longer consume fuel when trucks are waiting for place to deliver cargo to.
