### ISSUE TITLE
Crash when launching saved game

### ISSUE THREAD

**Issue by godifreyI** [MaFi-Games/Captain-of-Industry-issues#851]
### Issue description

Crash when launching saved game.
Sometimes game start and it's ok, sometimes hard crash of the game.

### Expected behavior

Save launched correctly

### Reproduction steps

Start game
Click to continue

### Game version

V0.4.12e

### Attachments

![Erreur](https://user-images.githubusercontent.com/7627229/193336059-83d233fc-f951-4fee-9938-ea89adc948cf.png)

**Comment by zuff-coi** [comment]
Sorry to hear this happening to you, @godifreyI ! Would you mind uploading your logs and save file?

You'll find your saved games in `"Documents\Captain of Industry\Saves"` but you'll need to zip it in order to upload it to github.

You can find your logs in 

`"Documents\Captain of Industry\Logs"`

and

`%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`

**Comment by zuff-coi** [comment]
I've also been told this is a memory error, could you provide your computer specs? CPU, Memory, GPU?

**Comment by MaFi-Games** [comment]
Closing as not enough information to investigate.
