### ISSUE TITLE
diggin on a beachc leads to nightmares

### ISSUE THREAD

**Issue by bwadejs** [MaFi-Games/Captain-of-Industry-issues#94]
tried to level the beach in a few areas to make cargo potrs,  vehicles get stuck, trucks cant get to location and fuel trucks cant get there bringing whole system to a standstill.  save file attached.
current issue location is beach on bottom right, also tried at top of map, built a ramp down to beach but vehicles refuse to reach location so deleted mine buildin
[1.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7801375/1.zip)
g

**Comment by MaFi-Games** [comment]
Hi, thanks for your report and for attaching the save file. I have loaded it and observed your issues.

It is true that digging in sand is hard because it collapses a lot, but the main issue in your case was that the ramp down to the mining area and dock was very narrow and collapsed. To make your ramps more reliable, make them wider so that a small collapse of the sand won't block them.

Please let us know if you have any further issues.
