### ISSUE TITLE
Statue of Maintenance dont follow the math.

### ISSUE THREAD

**Issue by CrazyOdd** [MaFi-Games/Captain-of-Industry-issues#981]
Edit: Seems this is on Sailor difficulty, which gets double bonus...

---

Didnt the Statue of Maintenance start at 4%, then half for each one?
Meaning 5 statues should be: 4 + 2 + 1 + 0.5 + 0.25 = 7.75.

The statue need 6.0 maintenance before built. End result after 5 of them, is 5.2 maintenance needed.
Where does the extra 0.3 drop come from?

6.0 / 100 x 92.25 = 5.535 rounded to 5.5.
Even if the 0.5 and 0.25 counts as full 1%, that still only 9% total, not the 13%-ish you end up with.

I even went to the trouble of building 800+ of them, to test the math, but it stopped counting after the 5th one. 
Given the 6th would be 0.125%, the game rounds 3 digits after 0 to 0? 
I went that high, because I expected the game to round to the smallest number it could support.
Like, if it supported 4 digits as the lowest and rounded to it, 1000 statues extra would be 1% T2-T3 maintenance saved.

**Comment by Gottchar** [comment]
The game currently adds up all reductions, including those of difficulty. So if you play on Sailor (40% reduction) and have 2 statues, you end up with:

base value * (100-40-4-2)/100

An admiral doing the same end up with

base value * (100+20-4-2)/100

Due to this, once you have multiple effects, including edicts, the numbers get quite extreme 
A Sailor with who would need 6 maintenance for a building without edicts/statues goes down to 2.725 with 2 edicts and 5 statues
An Admiral would usually need 12 maintenance for the same building, but only goes down to 8.75 with 5 statues and 2 edicts.

Suggested solution: Mutiply reductions from different sources, but leave them additive from the same source

OLD: Base value * (100-difficultychange - statues - edicts)/100
NEW: base value * (100-difficultychange)/100 * (100-statues)/100 * (100-edicts)/100

**Comment by MaFi-Games** [comment]
Glad to report that this was fixed in Update 1. So closing as completed.
